// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#include "../ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Apps = NULL;
lv_obj_t * ui_AppItem = NULL;
lv_obj_t * ui_icon = NULL;
lv_obj_t * ui_name = NULL;
// event funtions
void ui_event_AppItem(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_Animation(ui_icon, 300);
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 300, &ui_Settings_screen_init);
    }
}

void ui_event_icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_Animation(ui_icon, 300);
    }
}

void ui_event_name(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_Animation(ui_icon, 300);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Apps = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Apps);
    lv_obj_set_width(ui_Apps, 320);
    lv_obj_set_height(ui_Apps, 480);
    lv_obj_set_align(ui_Apps, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Apps, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Apps, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Apps, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_AppItem = lv_obj_create(ui_Apps);
    lv_obj_remove_style_all(ui_AppItem);
    lv_obj_set_width(ui_AppItem, 80);
    lv_obj_set_height(ui_AppItem, 80);
    lv_obj_remove_flag(ui_AppItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon = lv_image_create(ui_AppItem);
    lv_image_set_src(ui_icon, &ui_img_images_settings_setting_png);
    lv_obj_set_width(ui_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_icon, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_icon, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_name = lv_label_create(ui_AppItem);
    lv_obj_set_width(ui_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_name, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_name, "Settings");

    lv_obj_add_event_cb(ui_icon, ui_event_icon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_name, ui_event_name, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AppItem, ui_event_AppItem, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_Apps = NULL;
    ui_AppItem = NULL;
    ui_icon = NULL;
    ui_name = NULL;

}
