// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Apps;
extern void ui_event_AppItem(lv_event_t * e);
extern lv_obj_t * ui_AppItem;
extern void ui_event_icon(lv_event_t * e);
extern lv_obj_t * ui_icon;
extern void ui_event_name(lv_event_t * e);
extern lv_obj_t * ui_name;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

