// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#include "../ui.h"

lv_obj_t * ui_POS_S2 = NULL;
lv_obj_t * ui_IMG_S2_Bg_1 = NULL;
lv_obj_t * ui_IMG_S2_Bg_2 = NULL;
lv_obj_t * ui_Label_Enter_Amount = NULL;
lv_obj_t * ui_Label_Want_to_pay = NULL;
lv_obj_t * ui_Panel_Amount = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Panel_Amount_table = NULL;
lv_obj_t * ui_Label_Amount_1 = NULL;
lv_obj_t * ui_Label_Amount_Pirce = NULL;
lv_obj_t * ui_BTN_Continue = NULL;
lv_obj_t * ui_Label_Continue = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_POS_S2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGOn_Animation(ui_IMG_S2_Bg_1, 0);
        BGOn_Animation(ui_IMG_S2_Bg_2, 100);
        FadeOn_Animation(ui_Label_Enter_Amount, 0);
        FadeOn_Animation(ui_Label_Want_to_pay, 100);
        FadeOn_Animation(ui_Panel_Amount, 150);
        FadeOnUp_Animation(ui_BTN_Continue, 200);
        Keyboard_Animation(ui_POS_S1, 250);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_1, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_2, 100);
        FadeOff_Animation(ui_POS_S1, 0);
        FadeOff_Animation(ui_BTN_Continue, 100);
        FadeOff_Animation(ui_Panel_Amount, 150);
        FadeOff_Animation(ui_Label_Want_to_pay, 200);
        FadeOff_Animation(ui_Label_Enter_Amount, 250);
    }
}

void ui_event_BTN_Continue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_POS_S3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 400, &ui_POS_S3_screen_init);
    }
}

// build funtions

void ui_POS_S2_screen_init(void)
{
    ui_POS_S2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_POS_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_1 = lv_image_create(ui_POS_S2);
    lv_image_set_src(ui_IMG_S2_Bg_1, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_1, LV_SIZE_CONTENT);   /// 272
    lv_obj_set_height(ui_IMG_S2_Bg_1, LV_SIZE_CONTENT);    /// 336
    lv_obj_set_x(ui_IMG_S2_Bg_1, -81);
    lv_obj_set_y(ui_IMG_S2_Bg_1, -267);
    lv_obj_set_align(ui_IMG_S2_Bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_S2_Bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_2 = lv_image_create(ui_POS_S2);
    lv_image_set_src(ui_IMG_S2_Bg_2, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_2, LV_SIZE_CONTENT);   /// 272
    lv_obj_set_height(ui_IMG_S2_Bg_2, LV_SIZE_CONTENT);    /// 336
    lv_obj_set_x(ui_IMG_S2_Bg_2, 158);
    lv_obj_set_y(ui_IMG_S2_Bg_2, 77);
    lv_obj_set_align(ui_IMG_S2_Bg_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_S2_Bg_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Enter_Amount = lv_label_create(ui_POS_S2);
    lv_obj_set_width(ui_Label_Enter_Amount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Enter_Amount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Enter_Amount, 0);
    lv_obj_set_y(ui_Label_Enter_Amount, 15);
    lv_obj_set_align(ui_Label_Enter_Amount, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Enter_Amount, "Enter\nAmount");
    lv_obj_set_style_text_color(ui_Label_Enter_Amount, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Enter_Amount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Enter_Amount, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Enter_Amount, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Want_to_pay = lv_label_create(ui_POS_S2);
    lv_obj_set_width(ui_Label_Want_to_pay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Want_to_pay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Want_to_pay, 0);
    lv_obj_set_y(ui_Label_Want_to_pay, 70);
    lv_obj_set_align(ui_Label_Want_to_pay, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Want_to_pay, "Enter the amount you want to pay");
    lv_obj_set_style_text_color(ui_Label_Want_to_pay, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Want_to_pay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Want_to_pay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Want_to_pay, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Amount = lv_obj_create(ui_POS_S2);
    lv_obj_set_height(ui_Panel_Amount, 80);
    lv_obj_set_width(ui_Panel_Amount, lv_pct(100));
    lv_obj_set_x(ui_Panel_Amount, 0);
    lv_obj_set_y(ui_Panel_Amount, 106);
    lv_obj_set_align(ui_Panel_Amount, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_Amount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Amount, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Amount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Amount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Amount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Amount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Panel_Amount);
    lv_obj_set_height(ui_TextArea1, 56);
    lv_obj_set_width(ui_TextArea1, lv_pct(100));
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    if("0123456789.+-" == "") lv_textarea_set_accepted_chars(ui_TextArea1, NULL);
    else lv_textarea_set_accepted_chars(ui_TextArea1, "0123456789.+-");
    lv_textarea_set_max_length(ui_TextArea1, 16);
    lv_textarea_set_placeholder_text(ui_TextArea1, "1.99");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextArea1, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextArea1, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Amount_table = lv_obj_create(ui_Panel_Amount);
    lv_obj_set_height(ui_Panel_Amount_table, 20);
    lv_obj_set_width(ui_Panel_Amount_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_Amount_table, 18);
    lv_obj_set_y(ui_Panel_Amount_table, -10);
    lv_obj_remove_flag(ui_Panel_Amount_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_Amount_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Amount_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Amount_table, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Amount_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Amount_table, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Amount_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Amount_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Amount_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Amount_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Amount_1 = lv_label_create(ui_Panel_Amount_table);
    lv_obj_set_width(ui_Label_Amount_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Amount_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Amount_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Amount_1, "Amount");
    lv_obj_set_style_text_color(ui_Label_Amount_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Amount_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Amount_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Amount_1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Amount_Pirce = lv_label_create(ui_Panel_Amount);
    lv_obj_set_width(ui_Label_Amount_Pirce, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Amount_Pirce, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Amount_Pirce, -101);
    lv_obj_set_y(ui_Label_Amount_Pirce, 4);
    lv_obj_set_align(ui_Label_Amount_Pirce, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Amount_Pirce, "$");
    lv_obj_set_style_text_font(ui_Label_Amount_Pirce, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Continue = lv_obj_create(ui_POS_S2);
    lv_obj_set_width(ui_BTN_Continue, 246);
    lv_obj_set_height(ui_BTN_Continue, 50);
    lv_obj_set_x(ui_BTN_Continue, 0);
    lv_obj_set_y(ui_BTN_Continue, 196);
    lv_obj_set_align(ui_BTN_Continue, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_BTN_Continue, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Continue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Continue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Continue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Continue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Continue, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Continue, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Continue, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Continue, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Continue = lv_label_create(ui_BTN_Continue);
    lv_obj_set_width(ui_Label_Continue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Continue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Continue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Continue, "CONTINUE");
    lv_obj_set_style_text_color(ui_Label_Continue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Continue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Continue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Continue, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_POS_S2);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_height(ui_Keyboard1, 220);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_BTN_Continue, ui_event_BTN_Continue, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_POS_S2, ui_event_POS_S2, LV_EVENT_ALL, NULL);

}

void ui_POS_S2_screen_destroy(void)
{
    if(ui_POS_S2) lv_obj_del(ui_POS_S2);

    // NULL screen variables
    ui_POS_S2 = NULL;
    ui_IMG_S2_Bg_1 = NULL;
    ui_IMG_S2_Bg_2 = NULL;
    ui_Label_Enter_Amount = NULL;
    ui_Label_Want_to_pay = NULL;
    ui_Panel_Amount = NULL;
    ui_TextArea1 = NULL;
    ui_Panel_Amount_table = NULL;
    ui_Label_Amount_1 = NULL;
    ui_Label_Amount_Pirce = NULL;
    ui_BTN_Continue = NULL;
    ui_Label_Continue = NULL;
    ui_Keyboard1 = NULL;

}
