// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef UI_POS_S5_H
#define UI_POS_S5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_POS_S5
extern void ui_POS_S5_screen_init(void);
extern void ui_POS_S5_screen_destroy(void);
extern void ui_event_POS_S5(lv_event_t * e);
extern lv_obj_t * ui_POS_S5;
extern lv_obj_t * ui_IMG_S5_BG;
extern lv_obj_t * ui_IMG_Ok_1;
extern lv_obj_t * ui_IMG_Ok_2;
extern lv_obj_t * ui_Label_Succesful;
extern lv_obj_t * ui_Label_press_contimue;
extern void ui_event_BTN_Next_2(lv_event_t * e);
extern lv_obj_t * ui_BTN_Next_2;
extern lv_obj_t * ui_IMG_Arrow1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

