// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef UI_POS_S1_H
#define UI_POS_S1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_POS_S1
extern void ui_POS_S1_screen_init(void);
extern void ui_POS_S1_screen_destroy(void);
extern void ui_event_POS_S1(lv_event_t * e);
extern lv_obj_t * ui_POS_S1;
extern lv_obj_t * ui_IMG_S1_BG;
extern lv_obj_t * ui_Circle_1;
extern lv_obj_t * ui_Circle_2;
extern lv_obj_t * ui_IMG_POS;
extern lv_obj_t * ui_Label_card_and_crypto;
extern lv_obj_t * ui_Label_Lets_get;
extern void ui_event_BTN_Next(lv_event_t * e);
extern lv_obj_t * ui_BTN_Next;
extern lv_obj_t * ui_IMG_Arrow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

