// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef UI_POS_S4_H
#define UI_POS_S4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_POS_S4
extern void ui_POS_S4_screen_init(void);
extern void ui_POS_S4_screen_destroy(void);
extern void ui_event_POS_S4(lv_event_t * e);
extern lv_obj_t * ui_POS_S4;
extern lv_obj_t * ui_IMG_S2_Bg_5;
extern lv_obj_t * ui_IMG_S2_Bg_6;
extern lv_obj_t * ui_Label_Amount_Pirce2;
extern lv_obj_t * ui_Label_Amount_Title;
extern lv_obj_t * ui_Label_QR_ready;
extern void ui_event_IMG_QR_Code(lv_event_t * e);
extern lv_obj_t * ui_IMG_QR_Code;
extern lv_obj_t * ui_Label_BTC_Address;
extern void ui_event_Label_Cancel(lv_event_t * e);
extern lv_obj_t * ui_Label_Cancel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

