// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#include "../ui.h"

lv_obj_t * ui_POS_S1 = NULL;
lv_obj_t * ui_IMG_S1_BG = NULL;
lv_obj_t * ui_Circle_1 = NULL;
lv_obj_t * ui_Circle_2 = NULL;
lv_obj_t * ui_IMG_POS = NULL;
lv_obj_t * ui_Label_card_and_crypto = NULL;
lv_obj_t * ui_Label_Lets_get = NULL;
lv_obj_t * ui_BTN_Next = NULL;
lv_obj_t * ui_IMG_Arrow = NULL;
// event funtions
void ui_event_POS_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGAnim_Animation(ui_IMG_S1_BG, 0);
        FadeOnOpa_Animation(ui_Circle_2, 50);
        FadeOnUp_Animation(ui_Circle_1, 200);
        FadeOn_Animation(ui_IMG_POS, 350);
        FadeOnUp_Animation(ui_Label_card_and_crypto, 0);
        FadeOnUp_Animation(ui_Label_Lets_get, 150);
        FadeOnUp_Animation(ui_BTN_Next, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S1_BG, 0);
        FadeOff_Animation(ui_Circle_1, 50);
        FadeOff_Animation(ui_IMG_POS, 150);
        FadeOff_Animation(ui_Label_card_and_crypto, 200);
        FadeOff_Animation(ui_Label_Lets_get, 250);
        _ui_opacity_set(ui_Circle_2, 0);
        FadeOff_Animation(ui_BTN_Next, 300);
    }
}

void ui_event_BTN_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_POS_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_POS_S2_screen_init);
    }
}

// build funtions

void ui_POS_S1_screen_init(void)
{
    ui_POS_S1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_POS_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S1_BG = lv_image_create(ui_POS_S1);
    lv_image_set_src(ui_IMG_S1_BG, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S1_BG, LV_SIZE_CONTENT);   /// 272
    lv_obj_set_height(ui_IMG_S1_BG, LV_SIZE_CONTENT);    /// 336
    lv_obj_set_align(ui_IMG_S1_BG, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_S1_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_S1_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_IMG_S1_BG, 136, 168);

    ui_Circle_1 = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_Circle_1, 170);
    lv_obj_set_height(ui_Circle_1, 170);
    lv_obj_set_x(ui_Circle_1, 0);
    lv_obj_set_y(ui_Circle_1, -100);
    lv_obj_set_align(ui_Circle_1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Circle_1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Circle_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle_2 = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_Circle_2, 200);
    lv_obj_set_height(ui_Circle_2, 200);
    lv_obj_set_x(ui_Circle_2, 0);
    lv_obj_set_y(ui_Circle_2, -100);
    lv_obj_set_align(ui_Circle_2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Circle_2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Circle_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Circle_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_POS = lv_image_create(ui_POS_S1);
    lv_image_set_src(ui_IMG_POS, &ui_img_img_pos_png);
    lv_obj_set_width(ui_IMG_POS, 124);
    lv_obj_set_height(ui_IMG_POS, 165);
    lv_obj_set_x(ui_IMG_POS, 0);
    lv_obj_set_y(ui_IMG_POS, 50);
    lv_obj_set_align(ui_IMG_POS, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_POS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_POS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IMG_POS, LV_IMAGE_ALIGN_TILE);

    ui_Label_card_and_crypto = lv_label_create(ui_POS_S1);
    lv_obj_set_width(ui_Label_card_and_crypto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_card_and_crypto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_card_and_crypto, 0);
    lv_obj_set_y(ui_Label_card_and_crypto, -150);
    lv_obj_set_align(ui_Label_card_and_crypto, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_card_and_crypto, "Card and Crypto\nPayment Solution");
    lv_obj_set_style_text_color(ui_Label_card_and_crypto, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_card_and_crypto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_card_and_crypto, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_card_and_crypto, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Lets_get = lv_label_create(ui_POS_S1);
    lv_obj_set_width(ui_Label_Lets_get, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Lets_get, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Lets_get, 0);
    lv_obj_set_y(ui_Label_Lets_get, -110);
    lv_obj_set_align(ui_Label_Lets_get, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Lets_get, "Let's get to work");
    lv_obj_set_style_text_color(ui_Label_Lets_get, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Lets_get, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Lets_get, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Lets_get, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Next = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_BTN_Next, 60);
    lv_obj_set_height(ui_BTN_Next, 60);
    lv_obj_set_x(ui_BTN_Next, 0);
    lv_obj_set_y(ui_BTN_Next, -20);
    lv_obj_set_align(ui_BTN_Next, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_BTN_Next, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Next, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_IMG_Arrow = lv_image_create(ui_BTN_Next);
    lv_image_set_src(ui_IMG_Arrow, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Next, ui_event_BTN_Next, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_POS_S1, ui_event_POS_S1, LV_EVENT_ALL, NULL);

}

void ui_POS_S1_screen_destroy(void)
{
    if(ui_POS_S1) lv_obj_del(ui_POS_S1);

    // NULL screen variables
    ui_POS_S1 = NULL;
    ui_IMG_S1_BG = NULL;
    ui_Circle_1 = NULL;
    ui_Circle_2 = NULL;
    ui_IMG_POS = NULL;
    ui_Label_card_and_crypto = NULL;
    ui_Label_Lets_get = NULL;
    ui_BTN_Next = NULL;
    ui_IMG_Arrow = NULL;

}
