// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef UI_POS_S2_H
#define UI_POS_S2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_POS_S2
extern void ui_POS_S2_screen_init(void);
extern void ui_POS_S2_screen_destroy(void);
extern void ui_event_POS_S2(lv_event_t * e);
extern lv_obj_t * ui_POS_S2;
extern lv_obj_t * ui_IMG_S2_Bg_1;
extern lv_obj_t * ui_IMG_S2_Bg_2;
extern lv_obj_t * ui_Label_Enter_Amount;
extern lv_obj_t * ui_Label_Want_to_pay;
extern lv_obj_t * ui_Panel_Amount;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Panel_Amount_table;
extern lv_obj_t * ui_Label_Amount_1;
extern lv_obj_t * ui_Label_Amount_Pirce;
extern void ui_event_BTN_Continue(lv_event_t * e);
extern lv_obj_t * ui_BTN_Continue;
extern lv_obj_t * ui_Label_Continue;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

