// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef UI_POS_S3_H
#define UI_POS_S3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_POS_S3
extern void ui_POS_S3_screen_init(void);
extern void ui_POS_S3_screen_destroy(void);
extern void ui_event_POS_S3(lv_event_t * e);
extern lv_obj_t * ui_POS_S3;
extern lv_obj_t * ui_IMG_S2_Bg_3;
extern lv_obj_t * ui_IMG_S2_Bg_4;
extern lv_obj_t * ui_Label_Select_Payment;
extern lv_obj_t * ui_Label_Ony_BTC;
extern lv_obj_t * ui_Panel_List_BTC;
extern void ui_event_Panel_List_Bg(lv_event_t * e);
extern lv_obj_t * ui_Panel_List_Bg;
extern lv_obj_t * ui_Panel_BTC_table;
extern lv_obj_t * ui_Label_Bitcoin;
extern lv_obj_t * ui_Label_BTC;
extern lv_obj_t * ui_IMG_BTC;
extern lv_obj_t * ui_IMG_Arrow_List_1;
extern lv_obj_t * ui_Panel_List_ETH;
extern lv_obj_t * ui_Panel_List_Bg1;
extern lv_obj_t * ui_Label_ETH;
extern lv_obj_t * ui_IMG_ETH;
extern lv_obj_t * ui_IMG_Arrow_List_2;
extern lv_obj_t * ui_Panel_ETH_table;
extern lv_obj_t * ui_Label_Ethereum;
extern lv_obj_t * ui_Panel_List_XRP;
extern lv_obj_t * ui_Panel_List_Bg2;
extern lv_obj_t * ui_Label_XRP;
extern lv_obj_t * ui_IMG_XRP;
extern lv_obj_t * ui_IMG_Arrow_List_3;
extern lv_obj_t * ui_Panel_XRP_table;
extern lv_obj_t * ui_Label_Ripple;
extern lv_obj_t * ui_Panel_List_Card;
extern lv_obj_t * ui_Panel_List_Bg3;
extern lv_obj_t * ui_Label_Card;
extern lv_obj_t * ui_IMG_XRP1;
extern lv_obj_t * ui_IMG_Arrow_List_4;
extern lv_obj_t * ui_Panel_Caed_table;
extern lv_obj_t * ui_Label_Card1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

