// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#include "../ui.h"

lv_obj_t * ui_POS_S3 = NULL;
lv_obj_t * ui_IMG_S2_Bg_3 = NULL;
lv_obj_t * ui_IMG_S2_Bg_4 = NULL;
lv_obj_t * ui_Label_Select_Payment = NULL;
lv_obj_t * ui_Label_Ony_BTC = NULL;
lv_obj_t * ui_Panel_List_BTC = NULL;
lv_obj_t * ui_Panel_List_Bg = NULL;
lv_obj_t * ui_Panel_BTC_table = NULL;
lv_obj_t * ui_Label_Bitcoin = NULL;
lv_obj_t * ui_Label_BTC = NULL;
lv_obj_t * ui_IMG_BTC = NULL;
lv_obj_t * ui_IMG_Arrow_List_1 = NULL;
lv_obj_t * ui_Panel_List_ETH = NULL;
lv_obj_t * ui_Panel_List_Bg1 = NULL;
lv_obj_t * ui_Label_ETH = NULL;
lv_obj_t * ui_IMG_ETH = NULL;
lv_obj_t * ui_IMG_Arrow_List_2 = NULL;
lv_obj_t * ui_Panel_ETH_table = NULL;
lv_obj_t * ui_Label_Ethereum = NULL;
lv_obj_t * ui_Panel_List_XRP = NULL;
lv_obj_t * ui_Panel_List_Bg2 = NULL;
lv_obj_t * ui_Label_XRP = NULL;
lv_obj_t * ui_IMG_XRP = NULL;
lv_obj_t * ui_IMG_Arrow_List_3 = NULL;
lv_obj_t * ui_Panel_XRP_table = NULL;
lv_obj_t * ui_Label_Ripple = NULL;
lv_obj_t * ui_Panel_List_Card = NULL;
lv_obj_t * ui_Panel_List_Bg3 = NULL;
lv_obj_t * ui_Label_Card = NULL;
lv_obj_t * ui_IMG_XRP1 = NULL;
lv_obj_t * ui_IMG_Arrow_List_4 = NULL;
lv_obj_t * ui_Panel_Caed_table = NULL;
lv_obj_t * ui_Label_Card1 = NULL;
// event funtions
void ui_event_POS_S3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGOn_Animation(ui_IMG_S2_Bg_3, 0);
        BGOn_Animation(ui_IMG_S2_Bg_4, 200);
        FadeOn_Animation(ui_Label_Select_Payment, 0);
        FadeOn_Animation(ui_Label_Ony_BTC, 100);
        FadeOnUp_Animation(ui_Panel_List_Card, 0);
        FadeOnUp_Animation(ui_Panel_List_XRP, 100);
        FadeOnUp_Animation(ui_Panel_List_ETH, 200);
        FadeOnUp_Animation(ui_Panel_List_BTC, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_3, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_4, 100);
        FadeOff_Animation(ui_Label_Select_Payment, 0);
        FadeOff_Animation(ui_Label_Ony_BTC, 50);
        FadeOff_Animation(ui_Panel_List_BTC, 100);
        FadeOff_Animation(ui_Panel_List_ETH, 150);
        FadeOff_Animation(ui_Panel_List_XRP, 200);
        FadeOff_Animation(ui_Panel_List_Card, 250);
    }
}

void ui_event_Panel_List_Bg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_POS_S4, LV_SCR_LOAD_ANIM_FADE_ON, 50, 400, &ui_POS_S4_screen_init);
    }
}

// build funtions

void ui_POS_S3_screen_init(void)
{
    ui_POS_S3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_POS_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_3 = lv_image_create(ui_POS_S3);
    lv_image_set_src(ui_IMG_S2_Bg_3, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_3, LV_SIZE_CONTENT);   /// 272
    lv_obj_set_height(ui_IMG_S2_Bg_3, LV_SIZE_CONTENT);    /// 336
    lv_obj_set_x(ui_IMG_S2_Bg_3, -114);
    lv_obj_set_y(ui_IMG_S2_Bg_3, -308);
    lv_obj_set_align(ui_IMG_S2_Bg_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_S2_Bg_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_4 = lv_image_create(ui_POS_S3);
    lv_image_set_src(ui_IMG_S2_Bg_4, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_4, LV_SIZE_CONTENT);   /// 272
    lv_obj_set_height(ui_IMG_S2_Bg_4, LV_SIZE_CONTENT);    /// 336
    lv_obj_set_x(ui_IMG_S2_Bg_4, 145);
    lv_obj_set_y(ui_IMG_S2_Bg_4, 214);
    lv_obj_set_align(ui_IMG_S2_Bg_4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_S2_Bg_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Select_Payment = lv_label_create(ui_POS_S3);
    lv_obj_set_width(ui_Label_Select_Payment, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Select_Payment, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Select_Payment, 0);
    lv_obj_set_y(ui_Label_Select_Payment, 15);
    lv_obj_set_align(ui_Label_Select_Payment, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Select_Payment, "Select Payment\nMetod");
    lv_obj_set_style_text_color(ui_Label_Select_Payment, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Select_Payment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Select_Payment, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Select_Payment, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ony_BTC = lv_label_create(ui_POS_S3);
    lv_obj_set_width(ui_Label_Ony_BTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ony_BTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Ony_BTC, 0);
    lv_obj_set_y(ui_Label_Ony_BTC, 70);
    lv_obj_set_align(ui_Label_Ony_BTC, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Ony_BTC, "Only BTC payment is possible");
    lv_obj_set_style_text_color(ui_Label_Ony_BTC, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ony_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ony_BTC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ony_BTC, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_BTC = lv_obj_create(ui_POS_S3);
    lv_obj_set_height(ui_Panel_List_BTC, 84);
    lv_obj_set_width(ui_Panel_List_BTC, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_BTC, 0);
    lv_obj_set_y(ui_Panel_List_BTC, 106);
    lv_obj_set_align(ui_Panel_List_BTC, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_List_BTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_BTC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg = lv_obj_create(ui_Panel_List_BTC);
    lv_obj_set_height(ui_Panel_List_Bg, 70);
    lv_obj_set_width(ui_Panel_List_Bg, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg, lv_color_hex(0xFFCEB0), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Panel_List_Bg, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel_BTC_table = lv_obj_create(ui_Panel_List_BTC);
    lv_obj_set_height(ui_Panel_BTC_table, 20);
    lv_obj_set_width(ui_Panel_BTC_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_BTC_table, 18);
    lv_obj_set_y(ui_Panel_BTC_table, -10);
    lv_obj_remove_flag(ui_Panel_BTC_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_BTC_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_BTC_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_BTC_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_BTC_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_BTC_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_BTC_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_BTC_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Bitcoin = lv_label_create(ui_Panel_BTC_table);
    lv_obj_set_width(ui_Label_Bitcoin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Bitcoin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Bitcoin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Bitcoin, "Bitcoin");
    lv_obj_set_style_text_color(ui_Label_Bitcoin, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Bitcoin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Bitcoin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Bitcoin, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BTC = lv_label_create(ui_Panel_List_BTC);
    lv_obj_set_width(ui_Label_BTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BTC, 68);
    lv_obj_set_y(ui_Label_BTC, 6);
    lv_obj_set_align(ui_Label_BTC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_BTC, "BTC");
    lv_obj_set_style_text_color(ui_Label_BTC, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_BTC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BTC, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_BTC = lv_image_create(ui_Panel_List_BTC);
    lv_image_set_src(ui_IMG_BTC, &ui_img_img_btc_png);
    lv_obj_set_width(ui_IMG_BTC, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_BTC, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_BTC, 20);
    lv_obj_set_y(ui_IMG_BTC, 6);
    lv_obj_set_align(ui_IMG_BTC, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_BTC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_BTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_1 = lv_image_create(ui_Panel_List_BTC);
    lv_image_set_src(ui_IMG_Arrow_List_1, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_1, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_1, 6);
    lv_obj_set_align(ui_IMG_Arrow_List_1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_Arrow_List_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IMG_Arrow_List_1, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IMG_Arrow_List_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_ETH = lv_obj_create(ui_POS_S3);
    lv_obj_set_height(ui_Panel_List_ETH, 84);
    lv_obj_set_width(ui_Panel_List_ETH, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_ETH, 0);
    lv_obj_set_y(ui_Panel_List_ETH, 195);
    lv_obj_set_align(ui_Panel_List_ETH, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_List_ETH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_ETH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_ETH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_ETH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_ETH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_ETH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg1 = lv_obj_create(ui_Panel_List_ETH);
    lv_obj_set_height(ui_Panel_List_Bg1, 70);
    lv_obj_set_width(ui_Panel_List_Bg1, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg1, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg1, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg1, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel_List_Bg1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_List_Bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_List_Bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_List_Bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_List_Bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_ETH = lv_label_create(ui_Panel_List_Bg1);
    lv_obj_set_width(ui_Label_ETH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_ETH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_ETH, 68);
    lv_obj_set_y(ui_Label_ETH, 0);
    lv_obj_set_align(ui_Label_ETH, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_ETH, "ETH");
    lv_obj_set_style_text_color(ui_Label_ETH, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_ETH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_ETH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_ETH, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_ETH = lv_image_create(ui_Panel_List_Bg1);
    lv_image_set_src(ui_IMG_ETH, &ui_img_img_eth_png);
    lv_obj_set_width(ui_IMG_ETH, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_ETH, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_ETH, 20);
    lv_obj_set_y(ui_IMG_ETH, 0);
    lv_obj_set_align(ui_IMG_ETH, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_ETH, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_ETH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_2 = lv_image_create(ui_Panel_List_Bg1);
    lv_image_set_src(ui_IMG_Arrow_List_2, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_2, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_2, 0);
    lv_obj_set_align(ui_IMG_Arrow_List_2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_Arrow_List_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IMG_Arrow_List_2, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IMG_Arrow_List_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_ETH_table = lv_obj_create(ui_Panel_List_ETH);
    lv_obj_set_height(ui_Panel_ETH_table, 20);
    lv_obj_set_width(ui_Panel_ETH_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_ETH_table, 18);
    lv_obj_set_y(ui_Panel_ETH_table, -10);
    lv_obj_remove_flag(ui_Panel_ETH_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_ETH_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_ETH_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_ETH_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_ETH_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_ETH_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_ETH_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_ETH_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ethereum = lv_label_create(ui_Panel_ETH_table);
    lv_obj_set_width(ui_Label_Ethereum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ethereum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Ethereum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Ethereum, "Ethereum");
    lv_obj_set_style_text_color(ui_Label_Ethereum, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ethereum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ethereum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ethereum, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label_Ethereum, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_XRP = lv_obj_create(ui_POS_S3);
    lv_obj_set_height(ui_Panel_List_XRP, 84);
    lv_obj_set_width(ui_Panel_List_XRP, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_XRP, 0);
    lv_obj_set_y(ui_Panel_List_XRP, 285);
    lv_obj_set_align(ui_Panel_List_XRP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_List_XRP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_XRP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_XRP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_XRP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_XRP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_XRP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg2 = lv_obj_create(ui_Panel_List_XRP);
    lv_obj_set_height(ui_Panel_List_Bg2, 70);
    lv_obj_set_width(ui_Panel_List_Bg2, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg2, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg2, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel_List_Bg2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_XRP = lv_label_create(ui_Panel_List_Bg2);
    lv_obj_set_width(ui_Label_XRP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_XRP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_XRP, 68);
    lv_obj_set_y(ui_Label_XRP, 0);
    lv_obj_set_align(ui_Label_XRP, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_XRP, "XRP");
    lv_obj_set_style_text_color(ui_Label_XRP, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_XRP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_XRP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_XRP, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_XRP = lv_image_create(ui_Panel_List_Bg2);
    lv_image_set_src(ui_IMG_XRP, &ui_img_img_xrp_png);
    lv_obj_set_width(ui_IMG_XRP, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_XRP, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_XRP, 20);
    lv_obj_set_y(ui_IMG_XRP, 0);
    lv_obj_set_align(ui_IMG_XRP, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_XRP, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_XRP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_3 = lv_image_create(ui_Panel_List_Bg2);
    lv_image_set_src(ui_IMG_Arrow_List_3, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_3, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_3, 0);
    lv_obj_set_align(ui_IMG_Arrow_List_3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_Arrow_List_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IMG_Arrow_List_3, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IMG_Arrow_List_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_XRP_table = lv_obj_create(ui_Panel_List_XRP);
    lv_obj_set_height(ui_Panel_XRP_table, 20);
    lv_obj_set_width(ui_Panel_XRP_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_XRP_table, 18);
    lv_obj_set_y(ui_Panel_XRP_table, -10);
    lv_obj_remove_flag(ui_Panel_XRP_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_XRP_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_XRP_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_XRP_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_XRP_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_XRP_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_XRP_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_XRP_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ripple = lv_label_create(ui_Panel_XRP_table);
    lv_obj_set_width(ui_Label_Ripple, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ripple, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Ripple, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Ripple, "Ripple");
    lv_obj_set_style_text_color(ui_Label_Ripple, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ripple, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ripple, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ripple, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label_Ripple, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Card = lv_obj_create(ui_POS_S3);
    lv_obj_set_height(ui_Panel_List_Card, 84);
    lv_obj_set_width(ui_Panel_List_Card, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_Card, 0);
    lv_obj_set_y(ui_Panel_List_Card, 375);
    lv_obj_set_align(ui_Panel_List_Card, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_List_Card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_Card, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Card, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg3 = lv_obj_create(ui_Panel_List_Card);
    lv_obj_set_height(ui_Panel_List_Bg3, 70);
    lv_obj_set_width(ui_Panel_List_Bg3, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg3, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg3, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel_List_Bg3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Card = lv_label_create(ui_Panel_List_Bg3);
    lv_obj_set_width(ui_Label_Card, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Card, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Card, 68);
    lv_obj_set_y(ui_Label_Card, 0);
    lv_obj_set_align(ui_Label_Card, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Card, "Card");
    lv_obj_set_style_text_color(ui_Label_Card, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Card, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Card, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Card, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_XRP1 = lv_image_create(ui_Panel_List_Bg3);
    lv_image_set_src(ui_IMG_XRP1, &ui_img_img_card_png);
    lv_obj_set_width(ui_IMG_XRP1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_XRP1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_XRP1, 15);
    lv_obj_set_y(ui_IMG_XRP1, 0);
    lv_obj_set_align(ui_IMG_XRP1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_XRP1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_XRP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_4 = lv_image_create(ui_Panel_List_Bg3);
    lv_image_set_src(ui_IMG_Arrow_List_4, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_4, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_4, 0);
    lv_obj_set_align(ui_IMG_Arrow_List_4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IMG_Arrow_List_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IMG_Arrow_List_4, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IMG_Arrow_List_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Caed_table = lv_obj_create(ui_Panel_List_Card);
    lv_obj_set_height(ui_Panel_Caed_table, 20);
    lv_obj_set_width(ui_Panel_Caed_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_Caed_table, 18);
    lv_obj_set_y(ui_Panel_Caed_table, -10);
    lv_obj_remove_flag(ui_Panel_Caed_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_Caed_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Caed_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Caed_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Caed_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Caed_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Caed_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Caed_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Card1 = lv_label_create(ui_Panel_Caed_table);
    lv_obj_set_width(ui_Label_Card1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Card1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Card1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Card1, "Card");
    lv_obj_set_style_text_color(ui_Label_Card1, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Card1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Card1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Card1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label_Card1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel_List_Bg, ui_event_Panel_List_Bg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_POS_S3, ui_event_POS_S3, LV_EVENT_ALL, NULL);

}

void ui_POS_S3_screen_destroy(void)
{
    if(ui_POS_S3) lv_obj_del(ui_POS_S3);

    // NULL screen variables
    ui_POS_S3 = NULL;
    ui_IMG_S2_Bg_3 = NULL;
    ui_IMG_S2_Bg_4 = NULL;
    ui_Label_Select_Payment = NULL;
    ui_Label_Ony_BTC = NULL;
    ui_Panel_List_BTC = NULL;
    ui_Panel_List_Bg = NULL;
    ui_Panel_BTC_table = NULL;
    ui_Label_Bitcoin = NULL;
    ui_Label_BTC = NULL;
    ui_IMG_BTC = NULL;
    ui_IMG_Arrow_List_1 = NULL;
    ui_Panel_List_ETH = NULL;
    ui_Panel_List_Bg1 = NULL;
    ui_Label_ETH = NULL;
    ui_IMG_ETH = NULL;
    ui_IMG_Arrow_List_2 = NULL;
    ui_Panel_ETH_table = NULL;
    ui_Label_Ethereum = NULL;
    ui_Panel_List_XRP = NULL;
    ui_Panel_List_Bg2 = NULL;
    ui_Label_XRP = NULL;
    ui_IMG_XRP = NULL;
    ui_IMG_Arrow_List_3 = NULL;
    ui_Panel_XRP_table = NULL;
    ui_Label_Ripple = NULL;
    ui_Panel_List_Card = NULL;
    ui_Panel_List_Bg3 = NULL;
    ui_Label_Card = NULL;
    ui_IMG_XRP1 = NULL;
    ui_IMG_Arrow_List_4 = NULL;
    ui_Panel_Caed_table = NULL;
    ui_Label_Card1 = NULL;

}
