// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_title = NULL;
lv_obj_t * ui_SettingList = NULL;
lv_obj_t * ui_SettingItem1 = NULL;
lv_obj_t * ui_SettingItem = NULL;
lv_obj_t * ui_SettingItem2 = NULL;
// event funtions
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_title = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, -76);
    lv_obj_set_y(ui_title, -209);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "Settings");
    lv_obj_set_style_text_font(ui_title, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingList = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_SettingList);
    lv_obj_set_width(ui_SettingList, 320);
    lv_obj_set_height(ui_SettingList, 420);
    lv_obj_set_align(ui_SettingList, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_SettingList, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_SettingList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingList, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingList, LV_DIR_VER);

    ui_SettingItem1 = ui_SettingItem_create(ui_SettingList);
    lv_obj_set_x(ui_SettingItem1, 1);
    lv_obj_set_y(ui_SettingItem1, -164);

    ui_SettingItem = ui_SettingItem_create(ui_SettingList);
    lv_obj_set_x(ui_SettingItem, 1);
    lv_obj_set_y(ui_SettingItem, -164);

    ui_SettingItem2 = ui_SettingItem_create(ui_SettingList);
    lv_obj_set_x(ui_SettingItem2, 1);
    lv_obj_set_y(ui_SettingItem2, -164);

    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_title = NULL;
    ui_SettingList = NULL;
    ui_SettingItem1 = NULL;
    ui_SettingItem = NULL;
    ui_SettingItem2 = NULL;

}
