// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#ifndef _UI_COMP_SETTINGNAME_H
#define _UI_COMP_SETTINGNAME_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SettingName
#define UI_COMP_SETTINGNAME_SETTINGNAME 0
#define UI_COMP_SETTINGNAME_ICON 1
#define UI_COMP_SETTINGNAME_ARROW 2
#define UI_COMP_SETTINGNAME_PROPERTY 3
#define _UI_COMP_SETTINGNAME_NUM 4
lv_obj_t * ui_SettingName_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
