// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#ifndef _UI_COMP_SETTINGITEM_H
#define _UI_COMP_SETTINGITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SettingItem
#define UI_COMP_SETTINGITEM_SETTINGITEM 0
#define UI_COMP_SETTINGITEM_ICON 1
#define UI_COMP_SETTINGITEM_ARROW 2
#define UI_COMP_SETTINGITEM_PROPERTY 3
#define _UI_COMP_SETTINGITEM_NUM 4
lv_obj_t * ui_SettingItem_create(lv_obj_t * comp_parent);
void ui_event_comp_SettingItem_SettingItem(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
