// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#include "../ui.h"

// COMPONENT SettingName

lv_obj_t * ui_SettingName_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SettingName;
    cui_SettingName = lv_button_create(comp_parent);
    lv_obj_set_width(cui_SettingName, 280);
    lv_obj_set_height(cui_SettingName, 49);
    lv_obj_set_x(cui_SettingName, 1);
    lv_obj_set_y(cui_SettingName, -164);
    lv_obj_set_align(cui_SettingName, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_SettingName, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_SettingName, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_SettingName, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_icon;
    cui_icon = lv_image_create(cui_SettingName);
    lv_image_set_src(cui_icon, &ui_img_images_settings_wifi_png);
    lv_obj_set_width(cui_icon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(cui_icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(cui_icon, -110);
    lv_obj_set_y(cui_icon, 0);
    lv_obj_set_align(cui_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_icon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_arrow;
    cui_arrow = lv_image_create(cui_SettingName);
    lv_image_set_src(cui_arrow, &ui_img_images_settings_r_arrow_png);
    lv_obj_set_width(cui_arrow, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(cui_arrow, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(cui_arrow, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_arrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_arrow, 230);

    lv_obj_t * cui_property;
    cui_property = lv_label_create(cui_SettingName);
    lv_obj_set_width(cui_property, 150);
    lv_obj_set_height(cui_property, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_property, 25);
    lv_obj_set_y(cui_property, 0);
    lv_obj_set_align(cui_property, LV_ALIGN_CENTER);
    lv_label_set_text(cui_property, "text");
    lv_obj_set_style_text_align(cui_property, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_property, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SETTINGNAME_NUM);
    children[UI_COMP_SETTINGNAME_SETTINGNAME] = cui_SettingName;
    children[UI_COMP_SETTINGNAME_ICON] = cui_icon;
    children[UI_COMP_SETTINGNAME_ARROW] = cui_arrow;
    children[UI_COMP_SETTINGNAME_PROPERTY] = cui_property;
    lv_obj_add_event_cb(cui_SettingName, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SettingName, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_SettingName_create_hook(cui_SettingName);
    return cui_SettingName;
}

