/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'applications' 
 * Target:  'applications' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* LVGL::LVGL&LVGL9:Display&ST LTDC@9.3.0 */
/* use display driver for ST LTDC */
#define LV_USE_ST_LTDC    1
/* LVGL::LVGL&LVGL9:Essential@9.3.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL


#endif /* RTE_COMPONENTS_H */
