// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: artpi

#ifndef _ARTPI_UI_H
#define _ARTPI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_Settings.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * touch_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_settings_setting_png);    // assets/images/settings/setting.png
LV_IMG_DECLARE(ui_img_images_settings_wifi_png);    // assets/images/settings/wifi.png
LV_IMG_DECLARE(ui_img_images_settings_r_arrow_png);    // assets/images/settings/r_arrow.png
LV_IMG_DECLARE(ui_img_images_settings_bt_png);    // assets/images/settings/bt.png
LV_IMG_DECLARE(ui_img_images_settings_setting128_png);    // assets/images/settings/setting128.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
