// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: POS

#ifndef _POS_UI_H
#define _POS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_POS_S1.h"
#include "screens/ui_POS_S2.h"
#include "screens/ui_POS_S3.h"
#include "screens/ui_POS_S4.h"
#include "screens/ui_POS_S5.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * FadeOn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * BGOn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FadeOnOpa_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FadeOnUp_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FadeOff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Keyboard_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * BGAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Ready_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ReadyOpa_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_bg_1_png);    // assets/IMG_BG_1.png
LV_IMG_DECLARE(ui_img_img_pos_png);    // assets/IMG_pos.png
LV_IMG_DECLARE(ui_img_img_arrow_right_png);    // assets/IMG_arrow_right.png
LV_IMG_DECLARE(ui_img_img_btc_png);    // assets/IMG_BTC.png
LV_IMG_DECLARE(ui_img_img_eth_png);    // assets/IMG_ETH.png
LV_IMG_DECLARE(ui_img_img_xrp_png);    // assets/IMG_XRP.png
LV_IMG_DECLARE(ui_img_img_card_png);    // assets/IMG_Card.png
LV_IMG_DECLARE(ui_img_img_qr_png);    // assets/IMG_QR.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png

// FONTS
LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
